import type { Metadata } from 'next'
import { Poppins, Playfair_Display } from 'next/font/google'
import './globals.css'
import LazyTrackingPixels from './components/LazyTrackingPixels'

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['400', '600', '700'], // Reduced from 6 weights to 3 critical weights only
  display: 'swap',
  preload: true,
  fallback: ['system-ui', 'sans-serif'],
})

const playfair = Playfair_Display({
  variable: '--font-playfair',
  subsets: ['latin'],
  weight: ['700', '900'], // Reduced from 3 weights to 2 (removed 400 - not used much)
  display: 'swap',
  preload: true,
  fallback: ['Georgia', 'serif'],
})

export const metadata: Metadata = {
  title: '7-Min AI Videos | 100+ Real Estate Leads UAE | $37',
  description:
    'UAE & Dubai real estate agents: Turn photos into AI talking videos in 7 min. Generate 15 leads/week. No camera needed. $37 course.',
  keywords:
    'AI video, real estate marketing, talking AI videos, lead generation, real estate agents, AI agent clone, video marketing, property listing videos',
  authors: [{ name: 'AI FastScale' }],
  creator: 'AI FastScale',
  publisher: 'AI FastScale',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  metadataBase: new URL('https://aifastscale.com'),
  alternates: {
    canonical: '/',
  },
  openGraph: {
    title:
      'AI FastScale – 7-Minute AgentClone™ | Turn Photos Into Talking AI Videos',
    description:
      'Turn a photo into a realistic talking AI video in 7 minutes. Get 5-15 leads this week, 100+ real buyer leads monthly. Built for real estate agents.',
    url: 'https://aifastscale.com',
    siteName: 'AI FastScale',
    images: [
      {
        url: '/images/P1_result.webp',
        width: 1200,
        height: 630,
        alt: 'AI FastScale - 7 Minute AgentClone Course',
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'AI FastScale – 7-Minute AgentClone™',
    description:
      'Turn a photo into a realistic talking AI video in 7 minutes. Get 5-15 leads this week. Built for real estate agents.',
    images: ['/images/P1_result.webp'],
    creator: '@aifastscale',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  // verification: {
  //   google: 'your-google-verification-code',
  // },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        {/* Resource hints for performance - Removed video preload (41MB!) */}

        {/* Hreflang Tags for International SEO */}
        <link rel="alternate" hrefLang="en" href="https://aifastscale.com" />
        <link rel="alternate" hrefLang="ar" href="https://aifastscale.com/ar" />
        <link rel="alternate" hrefLang="en-AE" href="https://aifastscale.com" />
        <link rel="alternate" hrefLang="ar-AE" href="https://aifastscale.com/ar" />
        <link rel="alternate" hrefLang="x-default" href="https://aifastscale.com" />

        {/* Favicons - Generated by RealFaviconGenerator */}
        <link
          rel="icon"
          type="image/png"
          href="/favicon-96x96.png"
          sizes="96x96"
        />
        <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
        <link rel="shortcut icon" href="/favicon.ico" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <meta name="apple-mobile-web-app-title" content="AI FastScale" />
        <link rel="manifest" href="/site.webmanifest" />

        {/* Google Merchant Center Verification */}
        <meta name="google-site-verification" content="07UTX0YRgm3QIW1-mgHhLSko642Dbkp4ksQEZNq3z5g" />

        {/* Complete Schema.org Markup - Product + FAQ + Organization + LocalBusiness + Video */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              '@context': 'https://schema.org',
              '@graph': [
                {
                  '@type': 'Product',
                  '@id': 'https://aifastscale.com/#product',
                  name: '7 Minute AgentClone',
                  description:
                    'Turn a photo into a realistic talking AI video in 7 minutes. Complete step-by-step blueprint for real estate agents to generate 100+ leads monthly.',
                  image: 'https://aifastscale.com/images/P1_result.webp',
                  brand: {
                    '@type': 'Brand',
                    name: 'AI FastScale',
                  },
                  offers: {
                    '@type': 'Offer',
                    url: 'https://aifastscale.com',
                    priceCurrency: 'USD',
                    price: '37',
                    availability: 'https://schema.org/InStock',
                    priceValidUntil: '2025-12-31',
                    seller: {
                      '@type': 'Organization',
                      name: 'AI FastScale',
                    },
                  },
                  aggregateRating: {
                    '@type': 'AggregateRating',
                    ratingValue: '4.9',
                    reviewCount: '500',
                    bestRating: '5',
                    worstRating: '1',
                  },
                },
                {
                  '@type': 'FAQPage',
                  '@id': 'https://aifastscale.com/#faq',
                  mainEntity: [
                    {
                      '@type': 'Question',
                      name: 'How long does it take to create an AI video?',
                      acceptedAnswer: {
                        '@type': 'Answer',
                        text: 'With the 7-Minute AgentClone system, you can create professional talking AI videos in just 7 minutes. No technical skills or filming required.',
                      },
                    },
                    {
                      '@type': 'Question',
                      name: 'Will this work for real estate agents in UAE and Dubai?',
                      acceptedAnswer: {
                        '@type': 'Answer',
                        text: 'Yes! The 7-Minute AgentClone works perfectly for UAE real estate agents in Dubai, Abu Dhabi, and Sharjah. Generate 5-15 leads per week with AI videos.',
                      },
                    },
                    {
                      '@type': 'Question',
                      name: 'Do I need to film myself or hire actors?',
                      acceptedAnswer: {
                        '@type': 'Answer',
                        text: 'No filming needed! Simply upload a photo and the AI creates a realistic talking video. Perfect for agents who want professional videos without being on camera.',
                      },
                    },
                    {
                      '@type': 'Question',
                      name: 'What is the refund policy?',
                      acceptedAnswer: {
                        '@type': 'Answer',
                        text: 'We offer a 30-day money-back guarantee. If you are not satisfied with the 7-Minute AgentClone course, request a full refund within 30 days.',
                      },
                    },
                    {
                      '@type': 'Question',
                      name: 'How many videos can I create?',
                      acceptedAnswer: {
                        '@type': 'Answer',
                        text: 'Unlimited! After the one-time $37 investment, create as many AI talking videos as you want at no extra cost. No monthly subscriptions.',
                      },
                    },
                  ],
                },
                {
                  '@type': 'Organization',
                  '@id': 'https://aifastscale.com/#organization',
                  name: 'AI FastScale',
                  url: 'https://aifastscale.com',
                  logo: {
                    '@type': 'ImageObject',
                    url: 'https://aifastscale.com/images/P1_result.webp',
                    width: 1200,
                    height: 630,
                  },
                  contactPoint: {
                    '@type': 'ContactPoint',
                    contactType: 'Customer Service',
                    areaServed: ['AE', 'SA', 'US', 'GB'],
                    availableLanguage: ['English', 'Arabic'],
                  },
                },
                {
                  '@type': 'LocalBusiness',
                  '@id': 'https://aifastscale.com/#localbusiness',
                  name: 'AI FastScale',
                  description:
                    'AI video creation platform for real estate agents in UAE. Turn photos into talking AI videos in 7 minutes.',
                  url: 'https://aifastscale.com',
                  address: {
                    '@type': 'PostalAddress',
                    addressLocality: 'Dubai',
                    addressRegion: 'Dubai',
                    addressCountry: 'AE',
                  },
                  geo: {
                    '@type': 'GeoCoordinates',
                    latitude: 25.2048,
                    longitude: 55.2708,
                  },
                  priceRange: '$37',
                  openingHours: 'Mo-Su 00:00-23:59',
                },
                {
                  '@type': 'VideoObject',
                  '@id': 'https://aifastscale.com/#herovideo',
                  name: '7-Minute AgentClone Demo - Turn Photos Into Talking AI Videos',
                  description:
                    'Watch how real estate agents create professional AI videos in 7 minutes to generate 100+ leads monthly.',
                  thumbnailUrl: 'https://aifastscale.com/images/P1_result.webp',
                  uploadDate: '2025-01-01',
                  duration: 'PT4M25S',
                  contentUrl: 'https://aifastscale.com/videos/Hero-VSL.mp4',
                  embedUrl: 'https://aifastscale.com',
                },
              ],
            }),
          }}
        />
      </head>
      <body
        className={`${poppins.variable} ${playfair.variable} min-h-screen bg-black text-white antialiased font-sans`}
      >
        {/* Lazy load tracking pixels after 3 seconds for performance */}
        <LazyTrackingPixels />
        {children}
      </body>
    </html>
  )
}
