// ============================================
// NICHE CONFIG: PSYCHOLOGISTS
// ============================================

import {
  PlayCircle, Target, Trophy, Zap, Gift, Flame, Crown, StickyNote, Bookmark,
  FileText, Calendar, DollarSign, Headphones, Users, Brain, Star,
  Megaphone, Search, MessageSquare, Video
} from 'lucide-react'
import { NicheConfig } from '../types'

export const psychologistsConfig: NicheConfig = {
  // Identity
  slug: 'psychologists',
  title: 'CloneYourself',
  subtitle: 'for Psychologists',
  supportEmail: 'support@aifastscale.com',

  // Theme - Teal/Cyan (calming mental health theme)
  theme: {
    primary: 'teal-500',
    primaryLight: 'cyan-500',
    accent: 'emerald-500',
    glowColor: 'rgba(20, 184, 166, 0.3)',
    glowColorLg: 'rgba(20, 184, 166, 0.4)',
    btnGradient: 'from-teal-500 to-cyan-500',
    heroGradient: 'from-teal-500/15 to-cyan-500/10',
  },

  // Expert
  expert: {
    name: 'Dr. Marcus Rivers',
    title: 'Licensed Clinical Psychologist, PhD',
    image: '/images/psychologist/dr-marcus.webp',
    quote: "After 15 years in private practice and helping thousands of clients overcome anxiety and depression, I realized the therapists who thrive aren't just skilled — they're visible. I built this system to help you reach the people who desperately need your help.",
  },

  // Welcome
  welcomeVideo: {
    wistiaId: 'myh13ayp9d',
    title: 'Welcome from Dr. Marcus',
    duration: '2 min',
  },
  socialProof: {
    studentCount: 750,
    rating: 4.9,
    reviewCount: 67,
    countriesServed: 15,
  },
  memberStats: {
    baseMembers: 750,
    startDate: new Date('2025-01-25'),
    dailyGrowthMin: 20,
    dailyGrowthMax: 40,
    activeMin: 245,
    activeMax: 680,
    seedOffset: 4000,
  },

  // Modules
  modules: [
    {
      id: 'module-1',
      number: 1,
      title: 'Scriptwriting with Your Therapist AI Mentor',
      description: "Learn how to use your personalized Therapist AI mentor to generate high-quality short-form video scripts, story ideas, and content plans in minutes.",
      duration: '3 min',
      durationMinutes: 3,
      wistiaId: 'myh13ayp9d',
      thumbnail: '/images/psychologist/module-1.webp',
      lessons: ['Write video scripts in minutes', 'Using Therapist Expert Copywriter AI', 'Get scripts for trust & appointments'],
      resources: [
        { name: 'Marcus - Psychologist Growth Mentor', url: 'https://chatgpt.com/g/g-6974ba45c9b4819183b251cfe6b68c27-marcus-the-psychologist-growth-mentor', type: 'link' },
      ],
    },
    {
      id: 'module-2',
      number: 2,
      title: 'Accounts You Need to Get Started',
      description: "Set up the essential tools. I'll show you exactly where to register, which plan to choose, and how to avoid mistakes.",
      duration: '5 min',
      durationMinutes: 5,
      wistiaId: 'lpkrdgr19e',
      thumbnail: '/images/psychologist/module-2.webp',
      lessons: ['Where to register', 'Which plan to choose', 'Avoiding common mistakes'],
      resources: [
        { name: 'Google AI Pro (1-month free trial)', url: 'https://one.google.com/about/google-ai-plans/', type: 'link' },
        { name: 'Google Flow (AI Video Tool)', url: 'https://labs.google/flow/about', type: 'link' },
      ],
    },
    {
      id: 'module-3',
      number: 3,
      title: 'How to Make Any Photo Talk',
      description: "Turn a single photo into a realistic talking video. The exact process, right settings, and how to avoid common errors.",
      duration: '6 min',
      durationMinutes: 6,
      wistiaId: 'n4lx79ecbo',
      thumbnail: '/images/psychologist/module-3.webp',
      lessons: ['The exact process', 'Right settings to use', 'Avoiding common errors'],
      resources: [
        { name: 'Psychologist AI Talking Video Prompt', url: '/products/psychologist/Therapist_AI_Video_Prompt.txt', type: 'file' },
      ],
    },
    {
      id: 'module-4',
      number: 4,
      title: 'Edit Your AI Video in Minutes',
      description: "Edit your AI videos quickly using simple tools like CapCut. No experience required.",
      duration: '4 min',
      durationMinutes: 4,
      wistiaId: 'j2reo83n4z',
      thumbnail: '/images/psychologist/module-4.webp',
      lessons: ['Combine clips easily', 'Add captions & music', 'Export ready-to-post video'],
      resources: [
        { name: 'Background Music Collection', url: '/products/psychologist/Background music/', type: 'folder' },
      ],
    },
    {
      id: 'module-5',
      number: 5,
      title: 'Create Multiple Realistic Images',
      description: "Generate multiple realistic images of yourself using one reference photo. Different styles, locations, outfits.",
      duration: '5 min',
      durationMinutes: 5,
      wistiaId: '0a48x7ur8z',
      thumbnail: '/images/psychologist/module-5.webp',
      lessons: ['Generate realistic images', 'Different styles & locations', 'Keep same identity'],
      resources: [
        { name: 'Psychologist AI Image Generation Prompt', url: '/products/psychologist/Therapist_AI_Image_Prompt.txt', type: 'file' },
      ],
    },
    {
      id: 'module-6',
      number: 6,
      title: 'Scaling & Automation',
      description: 'Build a content machine that runs on autopilot. Batch create videos and scale your production.',
      duration: '5 min',
      durationMinutes: 5,
      wistiaId: null,
      thumbnail: null,
      lessons: ['Batch creation', 'Content calendar', 'Scale without burnout'],
      comingSoon: true,
      resources: [],
    },
    {
      id: 'module-7',
      number: 7,
      title: 'Turn Reviews into Video Testimonials',
      description: 'Transform your written Google reviews into powerful AI video testimonials that build instant trust.',
      duration: '6 min',
      durationMinutes: 6,
      wistiaId: null,
      thumbnail: null,
      lessons: ['Extract best reviews', 'Create AI spokesperson', 'Add to your website & ads'],
      comingSoon: true,
      resources: [],
    },
    {
      id: 'module-8',
      number: 8,
      title: 'Mental Health Education Content',
      description: 'Create educational content that reduces stigma and positions you as the go-to expert in your specialty.',
      duration: '5 min',
      durationMinutes: 5,
      wistiaId: null,
      thumbnail: null,
      lessons: ['Topic selection', 'Stigma-reducing messaging', 'Compliance-friendly content'],
      comingSoon: true,
      resources: [],
    },
    {
      id: 'module-9',
      number: 9,
      title: 'Anxiety & Depression Content Series',
      description: 'Create a content series specifically for anxiety and depression that attracts your ideal clients.',
      duration: '7 min',
      durationMinutes: 7,
      wistiaId: null,
      thumbnail: null,
      lessons: ['Common struggles to address', 'Compassionate messaging', 'Call-to-action strategies'],
      comingSoon: true,
      resources: [],
    },
    {
      id: 'module-10',
      number: 10,
      title: 'Platform-Specific Strategies',
      description: 'Master TikTok, Instagram Reels, YouTube Shorts, and Facebook with mental health-specific strategies.',
      duration: '8 min',
      durationMinutes: 8,
      wistiaId: null,
      thumbnail: null,
      lessons: ['Best times to post', 'Platform algorithms', 'Hashtag strategies for therapists'],
      comingSoon: true,
      resources: [],
    },
    {
      id: 'module-11',
      number: 11,
      title: 'AI Appointment Follow-ups',
      description: 'Automate client communication with AI-powered scripts for calls, texts, and appointment reminders.',
      duration: '6 min',
      durationMinutes: 6,
      wistiaId: null,
      thumbnail: null,
      lessons: ['AI phone scripts', 'Automated text sequences', 'No-show recovery system'],
      comingSoon: true,
      resources: [],
    },
  ],

  // Bonuses
  bonuses: [
    { id: 'bonus-1', name: '100 Viral Mental Health Scripts', value: 397, icon: FileText, description: 'Copy-paste scripts that go viral on social media', category: 'Content', url: '/products/psychologist/bonuses/100-viral-scripts.pdf', image: '/images/psychologist/viral-scripts.webp' },
    { id: 'bonus-2', name: '365-Day Content Calendar', value: 297, icon: Calendar, description: 'Never run out of content ideas for a whole year', category: 'Planning', url: '/products/psychologist/bonuses/365-content-calendar.pdf', image: '/images/psychologist/social-templates.webp' },
    { id: 'bonus-3', name: 'High-Value Intake Scripts', value: 497, icon: DollarSign, description: 'Convert more consultations into ongoing clients', category: 'Sales', url: '/products/psychologist/bonuses/intake-scripts.pdf', image: '/images/psychologist/consultation-scripts.webp' },
    { id: 'bonus-4', name: 'Educational Content System', value: 397, icon: Brain, description: 'Create content that reduces stigma and attracts clients', category: 'Content', url: '/products/psychologist/bonuses/educational-content.pdf', image: '/images/psychologist/educational-content.webp' },
    { id: 'bonus-5', name: 'Intake Coordinator Phone Scripts', value: 397, icon: Headphones, description: 'Convert more phone calls into booked sessions', category: 'Operations', url: '/products/psychologist/bonuses/phone-scripts.pdf', image: '/images/psychologist/phone-scripts.webp' },
    { id: 'bonus-6', name: 'Insurance & Payment Scripts', value: 347, icon: FileText, description: 'Handle insurance questions with confidence', category: 'Sales', url: '/products/psychologist/bonuses/insurance-scripts.pdf', image: '/images/psychologist/insurance-scripts.webp' },
    { id: 'bonus-7', name: 'Referral Machine System', value: 447, icon: Users, description: 'Turn happy clients into your best referral source', category: 'Marketing', url: '/products/psychologist/bonuses/referral-system.pdf', image: '/images/psychologist/referral-machine.webp' },
    { id: 'bonus-8', name: 'AI Content Generator (500+ Prompts)', value: 297, icon: Brain, description: 'Never write content from scratch again', category: 'AI Tools', url: 'https://chatgpt.com/g/g-6974ba45c9b4819183b251cfe6b68c27-marcus-the-psychologist-growth-mentor', image: '/images/psychologist/ai-generator.webp' },
    { id: 'bonus-9', name: '5-Star Review System', value: 397, icon: Star, description: 'Get 20+ Google reviews every month on autopilot', category: 'Reviews', url: '/products/psychologist/bonuses/review-system.pdf', image: '/images/psychologist/review-explosion.webp' },
    { id: 'bonus-10', name: 'Group Therapy Launch System', value: 497, icon: Users, description: 'Scale your impact and income with groups', category: 'Operations', url: '/products/psychologist/bonuses/group-therapy.pdf', image: '/images/psychologist/group-therapy.webp' },
  ],

  // Achievements
  achievements: [
    { id: 'first-video', name: 'First Steps', description: 'Complete your first module', icon: PlayCircle, tier: 'bronze', points: 50 },
    { id: 'halfway', name: 'Halfway Hero', description: 'Complete 50% of the course', icon: Target, tier: 'silver', points: 100 },
    { id: 'completed', name: 'AI Video Master', description: 'Complete all modules', icon: Trophy, tier: 'gold', points: 250 },
    { id: 'fast-learner', name: 'Fast Learner', description: 'Complete 3 modules in one session', icon: Zap, tier: 'silver', points: 100 },
    { id: 'bonus-collector', name: 'Bonus Collector', description: 'Download 5 bonuses', icon: Gift, tier: 'bronze', points: 50 },
    { id: 'streak-3', name: '3-Day Streak', description: 'Learn 3 days in a row', icon: Flame, tier: 'bronze', points: 75 },
    { id: 'streak-7', name: 'Week Warrior', description: 'Learn 7 days in a row', icon: Crown, tier: 'gold', points: 200 },
    { id: 'note-taker', name: 'Note Taker', description: 'Write your first note', icon: StickyNote, tier: 'bronze', points: 25 },
    { id: 'bookworm', name: 'Bookworm', description: 'Bookmark 3 modules', icon: Bookmark, tier: 'bronze', points: 50 },
  ],

  // Coming Soon Courses
  comingSoonCourses: [
    {
      id: 'course-meta-ads',
      title: 'Meta Ads Mastery',
      subtitle: 'for Psychologists',
      description: 'Run profitable Facebook & Instagram ads that fill your appointment calendar. From $0 to your first 50 clients.',
      icon: Megaphone,
      color: 'from-teal-500 to-cyan-600',
      features: ['Facebook & Instagram Ads', 'Targeting therapy seekers', 'Ad creatives that convert', 'Budget optimization'],
      estimatedLaunch: 'Q1 2025',
      waitlistCount: 134,
      price: 397,
    },
    {
      id: 'course-google-ads',
      title: 'Google Ads Domination',
      subtitle: 'for Psychologists',
      description: 'Show up first when clients search "therapist near me". Capture high-intent leads ready to book.',
      icon: Search,
      color: 'from-amber-500 to-orange-600',
      features: ['Search ads setup', 'Local service ads', 'Keyword research', 'Landing page secrets'],
      estimatedLaunch: 'Q1 2025',
      waitlistCount: 112,
      price: 397,
    },
    {
      id: 'course-reviews',
      title: '5-Star Review Machine',
      subtitle: 'for Psychologists',
      description: 'Get 25+ Google reviews every month on autopilot. Build unstoppable social proof.',
      icon: Star,
      color: 'from-yellow-500 to-amber-600',
      features: ['Automated review requests', 'Response templates', 'Handling negative reviews', 'Review generation scripts'],
      estimatedLaunch: 'Q2 2025',
      waitlistCount: 189,
      price: 297,
    },
    {
      id: 'course-intake',
      title: 'High-Conversion Intake System',
      subtitle: 'for Psychologists',
      description: 'Convert more consultations into long-term clients. Master the intake process.',
      icon: DollarSign,
      color: 'from-green-500 to-emerald-600',
      features: ['Intake call mastery', 'Overcoming objections', 'Insurance presentation', 'Follow-up sequences'],
      estimatedLaunch: 'Q2 2025',
      waitlistCount: 256,
      price: 497,
    },
    {
      id: 'course-tiktok-reels',
      title: 'TikTok & Reels Viral System',
      subtitle: 'for Psychologists',
      description: 'Go viral with short-form mental health content. Turn views into booked sessions.',
      icon: Video,
      color: 'from-pink-500 to-rose-600',
      features: ['Viral content formulas', 'Trending sounds & hooks', 'Educational showcases', 'Building your brand'],
      estimatedLaunch: 'Q2 2025',
      waitlistCount: 198,
      price: 347,
    },
    {
      id: 'course-client-reactivation',
      title: 'Client Reactivation System',
      subtitle: 'for Psychologists',
      description: 'Bring back clients who stopped coming and unlock hidden revenue in your database.',
      icon: MessageSquare,
      color: 'from-cyan-500 to-teal-600',
      features: ['Email sequences', 'SMS campaigns', 'Recall scripts', 'Re-engagement offers'],
      estimatedLaunch: 'Q3 2025',
      waitlistCount: 98,
      price: 297,
    },
  ],

  // Keyboard shortcuts
  keyboardShortcuts: [
    { key: '←', action: 'Previous module' },
    { key: '→', action: 'Next module' },
    { key: 'Space', action: 'Play/Pause video' },
    { key: 'M', action: 'Mark module complete' },
    { key: 'N', action: 'Open notes' },
    { key: 'B', action: 'Toggle bookmark' },
    { key: 'D', action: 'Toggle dark mode' },
    { key: '?', action: 'Show shortcuts' },
    { key: 'Esc', action: 'Close modal' },
  ],

  // Auth
  auth: {
    product: 'psychologist',
    legacyPassword: 'therapy2026',
    legacyEnabled: true,
    vipGuests: [],
    whopCheckoutLink: '#',
    authStorageKey: 'psychologistMemberAuth',
  },
  blockedUsers: [],
  devAutoLogin: false,

  // Storage
  storagePrefix: 'psychologist_v4_',
}
